FILTER = [
    'actor',
    'actress',
    'additional crew',
    'animation department',
    'archive footage',
    'art department',
    'art director',
    'camera and electrical department',
    'casting department',
    'casting director',
    'cinematographer',
    'composer',
    'costume and wardrobe department',
    'costume designer',
    'director',
    'editorial department',
    'editor',
    'location manager',
    'makeup department',
    'music department',
    'producer',
    'production designer',
    'production manager',
    'script and continuity department',
    'second unit director or assistant director',
    'self',
    'set decorator',
    'sound department',
    'soundtrack',
    'special effects department',
    'stunts department',
    'transportation',
    'thanks',
    'visual effects department',
    'writer'
]